USE sports_ecommerce;

-- ============================================================
-- SPORTS E-COMMERCE SQL PROJECT
-- BEGINNER SQL QUERIES
-- Queries 1 - 20
-- ============================================================


-- ============================================================
-- QUERY 1
-- How many customers are in the database?
-- ============================================================

SELECT COUNT(*) AS total_customers
FROM customers;


-- ============================================================
-- QUERY 2
-- How many products are available?
-- ============================================================

SELECT COUNT(*) AS total_products
FROM products;


-- ============================================================
-- QUERY 3
-- How many sales transactions are recorded?
-- ============================================================

SELECT COUNT(*) AS total_sales
FROM sales;


-- ============================================================
-- QUERY 4
-- What is the total number of units sold?
-- ============================================================

SELECT SUM(OrderQuantity) AS total_units_sold
FROM sales;


-- ============================================================
-- QUERY 5
-- What is the total sales revenue?
-- ============================================================

SELECT ROUND(SUM(SalesAmount), 2) AS total_revenue
FROM sales;


-- ============================================================
-- QUERY 6
-- What is the average sales amount?
-- ============================================================

SELECT ROUND(AVG(SalesAmount), 2) AS average_sales_amount
FROM sales;


-- ============================================================
-- QUERY 7
-- What is the minimum and maximum product price?
-- ============================================================

SELECT
    MIN(ListPrice) AS minimum_product_price,
    MAX(ListPrice) AS maximum_product_price
FROM products;


-- ============================================================
-- QUERY 8
-- What are the 10 most expensive products?
-- ============================================================

SELECT
    ProductKey,
    ProductName,
    Category,
    SubCategory,
    ListPrice
FROM products
ORDER BY ListPrice DESC
LIMIT 10;


-- ============================================================
-- QUERY 9
-- What are the 10 cheapest products?
-- ============================================================

SELECT
    ProductKey,
    ProductName,
    Category,
    SubCategory,
    ListPrice
FROM products
ORDER BY ListPrice ASC
LIMIT 10;


-- ============================================================
-- QUERY 10
-- What product categories are available?
-- ============================================================

SELECT DISTINCT Category
FROM products
ORDER BY Category;


-- ============================================================
-- QUERY 11
-- What product subcategories are available?
-- ============================================================

SELECT DISTINCT SubCategory
FROM products
ORDER BY SubCategory;


-- ============================================================
-- QUERY 12
-- How many products are there in each category?
-- ============================================================

SELECT
    Category,
    COUNT(*) AS product_count
FROM products
GROUP BY Category
ORDER BY product_count DESC;


-- ============================================================
-- QUERY 13
-- How many products are there in each subcategory?
-- ============================================================

SELECT
    SubCategory,
    COUNT(*) AS product_count
FROM products
GROUP BY SubCategory
ORDER BY product_count DESC;


-- ============================================================
-- QUERY 14
-- What is the total revenue generated by each product?
-- ============================================================

SELECT
    p.ProductName,
    ROUND(SUM(s.SalesAmount), 2) AS total_revenue
FROM sales s
JOIN products p
    ON s.ProductKey = p.ProductKey
GROUP BY p.ProductKey, p.ProductName
ORDER BY total_revenue DESC;


-- ============================================================
-- QUERY 15
-- Which products sold the most units?
-- ============================================================

SELECT
    p.ProductName,
    SUM(s.OrderQuantity) AS total_units_sold
FROM sales s
JOIN products p
    ON s.ProductKey = p.ProductKey
GROUP BY p.ProductKey, p.ProductName
ORDER BY total_units_sold DESC
LIMIT 10;


-- ============================================================
-- QUERY 16
-- Which customers have made purchases?
-- ============================================================

SELECT DISTINCT
    c.CustomerKey,
    c.FullName
FROM customers c
JOIN sales s
    ON c.CustomerKey = s.CustomerKey
ORDER BY c.FullName;


-- ============================================================
-- QUERY 17
-- How much has each customer spent?
-- ============================================================

SELECT
    c.CustomerKey,
    c.FullName,
    ROUND(SUM(s.SalesAmount), 2) AS total_spent
FROM customers c
JOIN sales s
    ON c.CustomerKey = s.CustomerKey
GROUP BY c.CustomerKey, c.FullName
ORDER BY total_spent DESC;


-- ============================================================
-- QUERY 18
-- Who are the top 10 customers by total spending?
-- ============================================================

SELECT
    c.CustomerKey,
    c.FullName,
    ROUND(SUM(s.SalesAmount), 2) AS total_spent
FROM customers c
JOIN sales s
    ON c.CustomerKey = s.CustomerKey
GROUP BY c.CustomerKey, c.FullName
ORDER BY total_spent DESC
LIMIT 10;


-- ============================================================
-- QUERY 19
-- What is the total revenue by product category?
-- ============================================================

SELECT
    p.Category,
    ROUND(SUM(s.SalesAmount), 2) AS total_revenue
FROM sales s
JOIN products p
    ON s.ProductKey = p.ProductKey
GROUP BY p.Category
ORDER BY total_revenue DESC;


-- ============================================================
-- QUERY 20
-- What is the total profit generated from sales?
-- Profit = Sales Amount - Total Product Cost
-- ============================================================

SELECT
    ROUND(
        SUM(SalesAmount - TotalProductCost),
        2
    ) AS total_profit
FROM sales;


-- ============================================================
-- END OF BEGINNER QUERIES
-- ============================================================