USE sports_ecommerce;

-- ============================================================
-- SPORTS E-COMMERCE SQL PROJECT
-- INTERMEDIATE SQL QUERIES
-- Queries 21 - 30
-- ============================================================


-- ============================================================
-- QUERY 21
-- What is the total revenue generated by each product subcategory?
-- ============================================================

SELECT
    p.SubCategory,
    ROUND(SUM(s.SalesAmount), 2) AS total_revenue
FROM sales s
JOIN products p
    ON s.ProductKey = p.ProductKey
GROUP BY p.SubCategory
ORDER BY total_revenue DESC;


-- ============================================================
-- QUERY 22
-- What is the total profit generated by each product?
-- Profit = Sales Amount - Total Product Cost
-- ============================================================

SELECT
    p.ProductKey,
    p.ProductName,
    ROUND(SUM(s.SalesAmount - s.TotalProductCost), 2) AS total_profit
FROM sales s
JOIN products p
    ON s.ProductKey = p.ProductKey
GROUP BY p.ProductKey, p.ProductName
ORDER BY total_profit DESC;


-- ============================================================
-- QUERY 23
-- What are the top 10 most profitable products?
-- ============================================================

SELECT
    p.ProductKey,
    p.ProductName,
    ROUND(SUM(s.SalesAmount - s.TotalProductCost), 2) AS total_profit
FROM sales s
JOIN products p
    ON s.ProductKey = p.ProductKey
GROUP BY p.ProductKey, p.ProductName
ORDER BY total_profit DESC
LIMIT 10;


-- ============================================================
-- QUERY 24
-- What is the total revenue generated by each customer?
-- ============================================================

SELECT
    c.CustomerKey,
    c.FullName,
    ROUND(SUM(s.SalesAmount), 2) AS total_revenue
FROM customers c
JOIN sales s
    ON c.CustomerKey = s.CustomerKey
GROUP BY c.CustomerKey, c.FullName
ORDER BY total_revenue DESC;


-- ============================================================
-- QUERY 25
-- Which customers have made more than one purchase?
-- ============================================================

SELECT
    c.CustomerKey,
    c.FullName,
    COUNT(s.SalesID) AS number_of_purchases
FROM customers c
JOIN sales s
    ON c.CustomerKey = s.CustomerKey
GROUP BY c.CustomerKey, c.FullName
HAVING COUNT(s.SalesID) > 1
ORDER BY number_of_purchases DESC;


-- ============================================================
-- QUERY 26
-- Which products generated more than 1,000 in total revenue?
-- ============================================================

SELECT
    p.ProductKey,
    p.ProductName,
    ROUND(SUM(s.SalesAmount), 2) AS total_revenue
FROM products p
JOIN sales s
    ON p.ProductKey = s.ProductKey
GROUP BY p.ProductKey, p.ProductName
HAVING SUM(s.SalesAmount) > 1000
ORDER BY total_revenue DESC;


-- ============================================================
-- QUERY 27
-- What is the average order value?
-- ============================================================

SELECT
    ROUND(
        SUM(SalesAmount) / COUNT(DISTINCT SalesOrderNumber),
        2
    ) AS average_order_value
FROM sales;


-- ============================================================
-- QUERY 28
-- What is the total revenue generated each month?
-- ============================================================

SELECT
    DATE_FORMAT(
        STR_TO_DATE(OrderDate, '%Y-%m-%d'),
        '%Y-%m'
    ) AS sales_month,
    ROUND(SUM(SalesAmount), 2) AS monthly_revenue
FROM sales
GROUP BY sales_month
ORDER BY sales_month;


-- ============================================================
-- QUERY 29
-- What is the total number of units sold each month?
-- ============================================================

SELECT
    DATE_FORMAT(
        STR_TO_DATE(OrderDate, '%Y-%m-%d'),
        '%Y-%m'
    ) AS sales_month,
    SUM(OrderQuantity) AS total_units_sold
FROM sales
GROUP BY sales_month
ORDER BY sales_month;


-- ============================================================
-- QUERY 30
-- Which product categories generated the highest profit?
-- ============================================================

SELECT
    p.Category,
    ROUND(
        SUM(s.SalesAmount - s.TotalProductCost),
        2
    ) AS total_profit
FROM sales s
JOIN products p
    ON s.ProductKey = p.ProductKey
GROUP BY p.Category
ORDER BY total_profit DESC;


-- ============================================================
-- END OF INTERMEDIATE QUERIES
-- ============================================================